### ISSUE TITLE
请问博主如何解析ovkml格式

### ISSUE THREAD

**Issue by Thamkench** [Ricco1010/ricco#95]
看到博主提供的格式转换支持中包含ovkml，请问ovkml如何解析呢？我想本地实现ovkml转换成kml的功能，除了下载库能解析源代码吗，感谢回复

**Comment by Ricco1010** [comment]
@Thamkench 其实就是用这个方法一层一层解析https://github.com/Ricco1010/ricco/blob/master/src/ricco/etl/extract.py#L303
